TRAIN:
  ENABLE: False
  DATASET: epickitchens100
  BATCH_SIZE: 32
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: "/videos/code/slowfast-feats/checkpoints/SLOWFAST_8x8_R50.pkl"
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 1
  INPUT_CHANNEL_NUM: [3,3]
  READ_VID_FILE: True
  STRIDE: 16 
  PATH_TO_DATA_DIR: /home/shared_dataset/epic_kitchens_100_videos # "/videos/code/mmaction2/"
  PATH_PREFIX: ""
  VID_LIST: "epick100_videos_list_with_frames.txt"
  TMP_FOLDER: "frames_tmp"
  FPS: 30
  VID_FILE_EXT: ".mp4"
  SAMPLE_SIZE: [512, 288] # ffmpeg 512 x 288  # cv2: (288, 512)
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  REVERSE_INPUT_CHANNEL: False
MODEL:
  NUM_CLASSES: 400
  ARCH: slowfast
  MODEL_NAME: slowfast_r50
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: cataract-101
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
LOG_MODEL_INFO: False
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0

# MULTI_CROP:
#  LEFT: true
#  MIDDLE: false
#  RIGHT: false
#OUTPUT_DIR: "epickitchen_feats/left" # related to multicrop left,middle,right

# MULTI_CROP:
#  LEFT: false
#  MIDDLE: true
#  RIGHT: false
# OUTPUT_DIR: "epickitchen_feats/middle" # related to multicrop left,middle,right

MULTI_CROP:
  LEFT: false
  MIDDLE: false
  RIGHT: true
OUTPUT_DIR: "epickitchen_feats/right" # related to multicrop left,middle,right
